# Generated by Django 4.1.1 on 2022-11-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AppliancePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "appliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appliances.appliance",
                    ),
                ),
            ],
        ),
    ]
