# Generated by Django 4.1.1 on 2022-10-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=20)),
                ('appliance_purpose', models.CharField(choices=[('inspection', 'inspection'), ('repairing', 'repairing'), ('diagnostics', 'diagnostic')], max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
