# Generated by Django 4.1.1 on 2022-11-11 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("appliances", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliancephoto",
            name="image_added_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
