# Generated by Django 4.1.1 on 2022-11-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appliances", "0003_appliancephoto_image_added_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliance",
            name="creation_time",
            field=models.DateTimeField(),
        ),
    ]
