# Generated by Django 4.1.1 on 2023-01-07 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appliances", "0004_alter_appliance_creation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliance",
            name="creation_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 7, 20, 47, 51, 518820)
            ),
        ),
    ]
