# Generated by Django 4.1.1 on 2022-11-13 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField(blank=True)),
                ("part_addition_time", models.DateTimeField(auto_now_add=True)),
                (
                    "part_type",
                    models.CharField(
                        choices=[
                            ("Electronic", "Electronic"),
                            ("Water", "Water"),
                            ("Mechanical", "Mechanical"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("part_description", models.TextField()),
                (
                    "part_adder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_adder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectronicPart",
            fields=[
                (
                    "part_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="parts.part",
                    ),
                ),
                (
                    "surface_mount_technology",
                    models.CharField(
                        choices=[("SMT", "SMT"), ("THT", "THT")], max_length=20
                    ),
                ),
                ("pin_quantity", models.IntegerField()),
            ],
            bases=("parts.part",),
        ),
    ]
