# Generated by Django 4.1.1 on 2022-11-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="to_buy",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
