# Generated by Django 4.1.1 on 2022-11-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appliances", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("Inspection", "Inspection"),
                            ("Diagnostic", "Diagnostic"),
                            ("Repair", "Repair"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("task_description", models.TextField()),
                ("task_creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "task_appliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="appliances.appliance",
                    ),
                ),
            ],
        ),
    ]
