# Generated by Django 4.1.1 on 2022-10-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tast_creation_time',
            new_name='task_creation_time',
        ),
    ]
