# Generated by Django 4.1.1 on 2022-10-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '__first__'),
        ('task', '0002_rename_tast_creation_time_task_task_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_appliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='appliances.appliance'),
        ),
    ]
